### ISSUE TITLE
nextjs v12 bad-precaching-response

### ISSUE THREAD

**Issue by FDiskas** [shadowwalker/next-pwa#288] opened 2021-10-27 14:47 UTC
# Summary

Got error in console:
```
workbox-4a677df8.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://***.com/_next/server/middleware-manifest.json","status":404}]
```

# Versions

- `next-pwa`: v5.4.0
- `next`: v12.0.1

# How To Reproduce

1. Install the latest nextjs `npx create-next-app -e with-tailwindcss my-project`
2. delete `yarn.lock` file and install latest next and pwa `yarn add next@latest next-pwa`
3. create `next.config.js`
     ```js
    const withPWA = require('next-pwa')
    
    module.exports = withPWA({
      pwa: {
        dest: 'public'
      }
    })
    ```
3. run `yarn build`
4. run `yarn start`

See an error in console.

# Expected Behaviors

The file exists but is not accessible for some reason.
# Screenshots

![image](https://user-images.githubusercontent.com/468006/139089472-79bf1d7a-a085-415b-a14b-3dc65828e6df.png)

# Additional Context

Is it possible that this is related to some updates in nextjs.

**Comment by boatnerd** [comment] 2021-10-30 02:49
Btw, getting the same thing if you have _offline page defined. adding it to buildExcludes array works, but I don't think that should be excluded?

**Comment by LucaNerlich** [comment] 2021-10-30 21:53
just adding a +1, getting the same error.

**Comment by FDiskas** [comment] 2021-10-30 21:59
Add thumbs up and hit subscribe button. You don't need to ping everybody.
In my case provided workaround worked

**Comment by Fry98** [comment] 2021-10-31 19:18
> quick fix
> 
> **next.config.js**
> 
> ```js
> const withPWA = require("next-pwa");
> const runtimeCaching = require("next-pwa/cache");
> 
> module.exports = withPWA({
>   pwa: {
>     runtimeCaching,
>     buildExcludes: [/middleware-manifest.json$/]
>   },
> });
> ```

I don't think this would cause any issues in practice but there should probably be backslash before the dot inside the RegEx.
```
/middleware-manifest\.json$/
```

**Comment by TszHong0411** [comment] 2021-11-02 15:10
same issue for me

**Comment by TszHong0411** [comment] 2021-11-02 15:14
> > quick fix
> > **next.config.js**
> > ```js
> > const withPWA = require("next-pwa");
> > const runtimeCaching = require("next-pwa/cache");
> > 
> > module.exports = withPWA({
> >   pwa: {
> >     runtimeCaching,
> >     buildExcludes: [/middleware-manifest.json$/]
> >   },
> > });
> > ```
> 
> I don't think this would cause any issues in practice but there should probably be a backslash before the dot inside the RegEx.
> 
> ```
> /middleware-manifest\.json$/
> ```

Thank you, this method works

**Comment by thisisvilla** [comment] 2021-11-04 17:42
Hello!  This fix has worked for me, but lighthouse seems to break when trying to run a test. It hangs up forever and produces the following error:
`Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope...`

Any ideas? Thanks! 🙌

**Comment by Fry98** [comment] 2021-11-04 19:40
> Hello! This fix has worked for me, but lighthouse seems to break when trying to run a test. It hangs up forever and produces the following error: `Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope...`
> 
> Any ideas? Thanks! 🙌

Didn't notice this before but yeah, I've got the same issue.

**Comment by stopyransky** [comment] 2021-11-07 11:29
same issue just when bumping next.js version to 12.0.2, without using any _middleware

**Comment by mainak-ghosh** [comment] 2021-11-09 05:12
Faced the same issue with next version 12.0.2. Excluding middleware-manifest.json worked.

**Comment by GiovanniIncammicia** [comment] 2021-11-09 14:52
I'm having the same issue. I added buildExcludes on middleware-manifest.json as suggested, but now it's triggering the error on _middleware.js (and if I remove it, it triggers on _offline.js)

_middleware.js is bundled together with the other js files, so it's normal it can't find the file (true also for _offline.js).
By the way, I'm using Typescript and both files are in the pages directory.

Also, does anyone know how come I have a fallback-SOMECODE.js and workbox-SHORTCODE.js in my public folder along with the generated sw.js?
They are both minified and I'm not sure they should be in the codebase (but just generated in the bundle), am I wrong?

**Comment by Dovalization** [comment] 2021-11-09 17:37
Also facing this issue on next 12.0.3 and next-pwa 5.4.0.

> > Hello! This fix has worked for me, but lighthouse seems to break when trying to run a test. It hangs up forever and produces the following error: `Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope...`
> > Any ideas? Thanks! raised_hands
 
 Having this exact same problem, currently.

**Comment by DanielRios549** [comment] 2021-11-10 00:33
Same problem here, the requested middleware json file does not exist, neither a server folder inside _next exists, there are only __private and _static folder there.

**Comment by ksenginew** [comment] 2021-11-10 16:25
I got the same error and fixed with above workaround.

Then I got those errors with [Preact](https://preactjs.com/)+NextJS through [Preact plugin](https://github.com/preactjs/next-plugin-preact).
```js
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/chunks/framework-fad1cf520aaa9a55.js net::ERR_ABORTED 404
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/wTOm-zS7CDl9kBwvJRQ4u/_buildManifest.js net::ERR_ABORTED 404
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/wTOm-zS7CDl9kBwvJRQ4u/_ssgManifest.js net::ERR_ABORTED 404
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/chunks/main-509d6cba0a25ac9d.js net::ERR_ABORTED 404
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/chunks/pages/_app-b164ac5595c86b8a.js net::ERR_ABORTED 404
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/wTOm-zS7CDl9kBwvJRQ4u/_middlewareManifest.js net::ERR_ABORTED 404
ksengine.vercel.app/:1 
        
       GET https://ksengine.vercel.app/_next/static/chunks/pages/index-8edeb82041b633db.js net::ERR_ABORTED 404
```

and fixed by removing Preact. How can I fix this?

**Comment by elsigh** [comment] 2021-11-12 00:50
I had to change mine to 
```
buildExcludes: [
    /middleware-manifest\.json$/,
    /_middleware.js$/,
    /_middleware.js.map$/,
  ],
```

**Comment by DanielRios549** [comment] 2021-11-12 01:24
> I had to change mine to 
> ```
> buildExcludes: [
>     /middleware-manifest\.json$/,
>     /_middleware.js$/,
>     /_middleware.js.map$/,
>   ],
> ```

The _middleware.js is only necessary when using middleware, the manifest is always necessary

**Comment by SimHoZebs** [comment] 2021-11-13 04:04
Seems like the issue is with the service worker is trying to precache `middleware-manifest.json` from `/_next/server/`, but `/_next/server/` isn't served to the client..?

**Comment by EhsanKhalili** [comment] 2021-11-15 12:14
same issue with next version 12.0.1

![image](https://user-images.githubusercontent.com/11146415/141780178-df6129b0-0aff-45a5-af5d-696ea1f0e535.png)

**Comment by maxsupera** [comment] 2021-11-22 12:57
hello all! just checking back in to say the workaround below fixed the main issue for me, and the lighthouse issue seems to have been fixed with next `12.0.4` 
```
const withPWA = require("next-pwa");
const runtimeCaching = require("next-pwa/cache");

module.exports = withPWA({
  pwa: {
    runtimeCaching,
    buildExcludes: [/middleware-manifest\.json$/]
  },
});
```

**Comment by fredericrous** [comment] 2021-11-22 15:31
I had to exclude `_middleware.js` as well

```
module.exports = withPWA({
  pwa: {
    disable: process.env.NODE_ENV !== 'production',
    dest: 'public',
    register: true,
    skipWaiting: true,
    runtimeCaching,
    buildExcludes: [/middleware-manifest\.json$/, /_middleware\.js$/],
  },
});
```

and now I'm getting `VM3 sw.js:1 Uncaught (in promise) DOMException: Entry was not found.`

**Comment by francescopellegrini** [comment] 2021-11-23 07:42
Solved by v5.4.1?

**Comment by shadowwalker** [comment] 2021-11-23 08:07
> Solved by v5.4.1?

Should be solved so far

**Comment by amuttsch** [comment] 2021-11-23 08:22
I still encounter this issue with 5.4.1 using:

```
pwa: {
    dest: 'public'
}
```

**Comment by sfiquet** [comment] 2021-11-26 12:44
The fix in 5.4.1 doesn't work for me. I think the problem is the path. I found this object in `sw.js` (produced by `GenerateSW`): `{url:"/_next/server/middleware-manifest.json",revision:"RpdBZnMzs__SQLL5GD4jS"}`

The line
```
            if (asset.name.match(/^(build-manifest\.json|react-loadable-manifest\.json|middleware-manifest\.json)$/)) {
```
 works for `build-manifest.json` and `read-loadable-manifest.json` because they're at the root of the `.next` folder. Whereas `middleware-manifest.json` ends up in `.next/server`.

**Comment by francescopellegrini** [comment] 2021-11-26 20:39
Indeed @sfiquet , I'm experiencing the same issue.

**Comment by rtritto** [comment] 2021-11-26 21:04
Same _bad-precaching-response_ error with next.js v12.0.4 and next-pwa v5.4.1.

**Comment by ahurlburt** [comment] 2022-01-20 16:34
Does anyone know what the impact of excluding the `middleware-manifest.json` file as part of the build?

It does seem to fix issue by removing any references in the compiled `sw.js` file but I'm wary of just removing a file without understanding what it does...

**Comment by ksenginew** [comment] 2022-01-21 01:31
looks like #299  fixed this issue.

**Comment by hoangvu12** [comment] 2022-01-24 07:18
> buildExcludes: [/middleware-manifest\.json$/, /_middleware\.js$/],

This fixed my problem, I don't know if it cause any problem, but for now, it worked.

**Comment by MartsTech** [comment] 2022-01-25 16:45
Did anyone find a solution for _middleware.js file? No solution so far works for me.

**Comment by hoangvu12** [comment] 2022-01-26 05:11
> Did anyone find a solution for _middleware.js file? No solution so far works for me.

```js
buildExcludes: [/middleware-manifest.json$/, /_middleware.js$/]
```

Have you tried this?

**Comment by MartsTech** [comment] 2022-01-26 13:02
> > Did anyone find a solution for _middleware.js file? No solution so far works for me.
> 
> ```js
> buildExcludes: [/middleware-manifest.json$/, /_middleware.js$/]
> ```
> 
> Have you tried this?

I tried, but my problem wasn't resolved. I keep getting error in the console:
```
workbox-1846d813.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:3000/_next/server/middleware-runtime.js","status":404}]
```

**Comment by panddr** [comment] 2022-01-30 15:02
> > > Did anyone find a solution for _middleware.js file? No solution so far works for me.
> > 
> > 
> > ```js
> > buildExcludes: [/middleware-manifest.json$/, /_middleware.js$/]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have you tried this?
> 
> I tried, but my problem wasn't resolved. I keep getting error in the console:
> 
> ```
> workbox-1846d813.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:3000/_next/server/middleware-runtime.js","status":404}]
> ```

me too

**Comment by TimoWilhelm** [comment] 2022-01-30 15:10
`middleware-runtime.js` was introduced in a recent Next.js update. You can just add it to the exclude list. The full list of exlcudes for now seems to be:
```
buildExcludes: [
  /middleware-manifest\.json$/,
  /_middleware\.js$/,
  /_middleware\.js\.map$/,
  /middleware-runtime\.js$/,
],
```

**Comment by panddr** [comment] 2022-01-30 15:49
@TimoWilhelm it doesn't help with next 12.0.9 and next-pwa 5.4.4

**Comment by pascuflow** [comment] 2022-02-04 14:31
> @TimoWilhelm it doesn't help with next 12.0.9 and next-pwa 5.4.4

Same

**Comment by pascuflow** [comment] 2022-02-04 15:32
Can someone clone this repo https://github.com/shadowwalker/next-pwa and try something similar to this https://github.com/shadowwalker/next-pwa/commit/428546d6685af0ad777dc399e2f664de9c4a9595 on the index.js file, test the fix and submit an mr so we can all update?

**Comment by pascuflow** [comment] 2022-02-04 16:00
Nevermind, tried changing the line on index.js to `if (asset.name.match(/^(build-manifest\.json|react-loadable-manifest\.json|server\/middleware-manifest\.json|server\/middleware-runtime\.js)$/)) 
`, no luck, could it be because its on the _next/server instead of .next/server?

**Comment by pascuflow** [comment] 2022-02-10 05:18
Submitted a pr to fix this https://github.com/shadowwalker/next-pwa/pull/325

**Comment by ristomatti** [comment] 2022-02-18 12:09
@meotimdihia Now there seems to be some activity, hope is not lost!

**Comment by scglenn** [comment] 2022-02-21 19:58
I am having this issue still

**Comment by asihej** [comment] 2022-03-17 16:59
Still not working  😭
Using:
`"next": "^12.1.0"`
`"next-pwa": "^5.4.6"`

My config:
```
/** @type {import('next').NextConfig} */

const nextConfig = withPWA({
  reactStrictMode: process.env.NODE_ENV === "development",
  images: {
    deviceSizes: [360, 640, 750, 828, 1080, 1200],
  },
  pwa: {
    dest: "public",
    disable: process.env.NODE_ENV === "development",
  },
});
module.exports = nextConfig;
```
<img width="853" alt="Screenshot 2022-03-17 at 17 57 49" src="https://user-images.githubusercontent.com/44303255/158853837-4a1a29ef-b044-4182-a169-08873975cf52.png">

**Comment by FDiskas** [comment] 2022-03-18 07:07
@asihej why didn't you tried all suggestions?

**Comment by asihej** [comment] 2022-03-18 15:23
Hey @FDiskas to be honest, i've tried almost every single suggestion i have found so far. Sadly nothing works

**Comment by mariusc23** [comment] 2022-03-18 15:27
This is what worked for me in case it helps anyone:
```js
{
  pwa: {
    disable: process.env.NODE_ENV === "development",
    dest: "public",
    register: false,
    buildExcludes: [
      /middleware-manifest\.json$/,
      /_middleware\.js$/,
      /_middleware\.js\.map$/,
      /middleware-runtime\.js$/,
      /middleware-runtime\.js\.map$/,
    ],
  },
}
```

**Comment by patrik-meixner** [comment] 2022-03-29 11:46
When using nested middlewares and middleware-chunks, this has done the trick for me:

``` 
const withPwa = require('next-pwa');
const runtimeCaching = require('next-pwa/cache');

...
{
    pwa: {
        disable: process.env.NODE_ENV === 'development',
        dest: 'public',
        register: true,
        runtimeCaching,
        buildExcludes: [
            /\/*server\/middleware-chunks\/[0-9]*[a-z]*[A-Z]*\.js$/,
            /middleware-manifest\.json$/,
            /middleware-runtime\.js$/,
            /_middleware\.js$/,
            /^.+\\_middleware\.js$/,
        ],
        publicExcludes: ['!robots.txt'],
    }
}
...
```

**Comment by Manimall** [comment] 2022-03-30 17:20
not working(((

**Comment by maxsupera** [comment] 2022-04-03 21:50
one of the suggested fixes was working for a little while but has stopped working, and now nothing suggested in this thread is working at all. anyone have any clues?? thanks!

**Comment by shadowwalker** [comment] 2022-04-09 04:37
Should be working now with latest version and no `buildExcludes` config needed.

**Comment by meotimdihia** [comment] 2022-04-09 04:46
@shadowwalker thanks for your response. Please take a look at these pull requests: https://github.com/shadowwalker/next-pwa/pull/296
I think we should merge this if it works. Currently, I can't use currently pwa version because extra request at START URL. I have to fork to modify the source.

Everyone don't know this problem yet. And if they set it to `dynamicStartUrl` to `false` it'll break their apps. For example: https://github.com/shadowwalker/next-pwa/issues/315

**Comment by jonasmarco** [comment] 2022-04-14 01:33
![image](https://user-images.githubusercontent.com/19959770/163296358-444d886c-2437-4fea-ad8d-57c50a2833eb.png)
somebody?

**Closed** 2022-04-17 01:12 UTC
Labels: bug

**Comment by Manimall** [comment] 2022-05-06 17:11
@shadowwalker thanks a lot!!!! working!!!!!

**Comment by wztech0192** [comment] 2022-05-14 05:52
I'm using next 12.1.0, next-pwa 5.5.2 and all solutions doesnt work for me. As soon as I remove _middleware.js it start to work...

**Comment by mattvb91** [comment] 2022-08-11 11:52
@shadowwalker this issue exists again since the last release: 

```
workbox-e7ea62c2.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost/_next/static/KvFkEveQoLh_dME2rnKzW/_buildManifest.js","status":404}]
```

**Comment by gambolputty** [comment] 2022-08-11 15:29
Same here with:
- next@12.2.4
- next-pwa@5.5.5

![image](https://user-images.githubusercontent.com/8270488/184168811-d0eee56e-3fe4-4393-b4e0-9e53943342c4.png)

I'm also getting this warning:
> GenerateSW has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.

**Comment by jonasmarco** [comment] 2022-08-22 02:15
"next": "12.2.5",
    "next-pwa": "5.5.5",

![image](https://user-images.githubusercontent.com/19959770/185825586-b66d997f-26f5-4376-9aac-131cbd0d99f1.png)

[21/08/22]

**Comment by jonasmarco** [comment] 2022-08-22 02:17
@FDiskas

please reopen the issue as the same still happens

**Comment by malikarami** [comment] 2022-08-23 06:06
This issue is not fixed, I am using 5.2.24 and I am still getting this error sometimes.

**Comment by WGTW** [comment] 2022-08-30 12:32
Still not fixed in 5.6.0, getting a similar error myself:
`Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:8084/_next/static/503s2A1ywwygIF0aaUq6z/_buildManifest.js","status":404}]`

**Comment by josteph** [comment] 2022-09-06 04:30
@shadowwalker I think you need to add `middleware-manifest.json` into this line https://github.com/shadowwalker/next-pwa/blob/1e6af5fa9f6a807930f451adb5ab5078d5cda451/index.js#L217

**Comment by panddr** [comment] 2022-09-20 14:20
@shadowwalker This line causes this issue: https://github.com/shadowwalker/next-pwa/blob/1e6af5fa9f6a807930f451adb5ab5078d5cda451/index.js#L221 
It includes 2 server "/_next/build-manifest.json" and "/_next/react-loadable-manifest.json" into workbox.precacheAndRoute

**Comment by evert90** [comment] 2022-09-20 15:56
Using next 12.2.2 and next-pwa 5.4.7 solved for me

**Comment by iacobfred** [comment] 2022-10-22 17:14
I am still experiencing this issue with `"next-pwa": "5.6.0"` and `"next": "^12.3.2-canary.26"`:

```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://selfbuilder.dev.net/_next/static/2RXrQaPIzCmiQWV2lQJrv/_buildManifest.js","status":404}]
```

**Comment by PekayTab** [comment] 2022-11-27 05:37
I too am still having an issue with this 
![image](https://user-images.githubusercontent.com/36557751/204120943-c1d380f4-6e6e-4e92-9519-2fbd693ffbb8.png)
![image](https://user-images.githubusercontent.com/36557751/204120954-4abe436f-4846-4d23-b593-6730e70c8c10.png)

**Comment by ezekiel747** [comment] 2022-11-30 07:38
what if i don't have next-pwa at all in my project and still get this error?

**Comment by mattvb91** [comment] 2022-11-30 12:57
> what if i don't have next-pwa at all in my project and still get this error?

You probably still have the service worker installed. Delete the whole app cache and refresh

**Comment by ezekiel747** [comment] 2023-01-21 15:37
This doesn't seem related or caused by next-pwa itself.
I'm using next-offline instead, and get similar errors.

**Comment by Memeplexx** [comment] 2023-09-02 15:09
For me, this happened after:
1. I ran a build (locally) which created an `sw.js` file in my `/public` dir, and then
2. I ran `npm run dev`.

After manually deleting `sw.js` I no longer had issues.

I also updated my `package.json` as follows:
```
{
  "scripts": {
    "dev": "rm public/sw.js & next dev",
```

**Comment by Manishakoirala17** [comment] 2024-05-07 12:00
![Screenshot 2024-05-07 at 5 28 40 PM](https://github.com/shadowwalker/next-pwa/assets/107102215/c2c22223-39d2-4ced-8439-d9a1638c4639)

am using next js app router
next-pwa package 

"workbox-4a677df8.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://***.com/_next/server/middleware-manifest.json","status":404}]"

i got this error from my deploy url, how can i fix this?
please help me to fix this issue

**Comment by Manishakoirala17** [comment] 2024-05-07 12:03
my project in next-js app router - am using "next-pwa" module

"Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://selfbuilder.dev.net/_next/static/2RXrQaPIzCmiQWV2lQJrv/_buildManifest.js","status":404}]"

    "next-pwa": "^5.6.0",
    "next": "14.1.0",
    
    i have facing above issue in my deploy url, please help me to fix this.

**Comment by sundaram123krishnan** [comment] 2025-03-20 16:33
Still getting this issue
