### ISSUE TITLE
Image import urls don't get prefixed with _next

### ISSUE THREAD

**Issue by rafamel** [shadowwalker/next-pwa#225] opened 2021-06-17 14:34 UTC
# Summary

Importing assets -tested with *svg*- will cause them to lack the `_next` prefix to their url in `sw.js`.

# Versions

- `next-pwa`: 5.2.21
- `next`: 11.0.0

# How To Reproduce

1. Import and use an image on a *next@11*/*next-pwa* project: `import imageSrc from 'image/path.svg';`
2. Run `next build`
3. The url for the image at `sw.js` will not be prefixed with `_next`.
# Expected Behaviors

Imported assets get assigned the right path (`/_next/static`...).

# Screenshots

![image](https://user-images.githubusercontent.com/9166532/122417551-d969f080-cf89-11eb-8304-ae7c0d9719af.png)

![image](https://user-images.githubusercontent.com/9166532/122416458-09fd5a80-cf89-11eb-956d-230ca8f74af2.png)

**Comment by Balance8** [comment] 2021-06-21 18:18
Can confirm this is occurring on my project as well

**Comment by fillon** [comment] 2021-06-22 14:29
same for me

**Comment by rishabhrao** [comment] 2021-06-24 09:28
Any fixes for this Issue?
This bug is causing my SW registrations to fail. :(

**Comment by shadowwalker** [comment] 2021-07-05 17:37
I couldn't reproduce this error, could anyone create a minimal simple reproduce repo?

**Comment by Balance8** [comment] 2021-07-09 17:25
this appears to be fixed by upgrading to `next ^11.0.1` and `next-pwa ^5.2.23`.  I can confirm the /_next/static/ is being properly appended to imported images. 


![image](https://user-images.githubusercontent.com/36809369/125115201-d8ffd980-e09f-11eb-8e86-1f5a93ba9dd2.png)

**Comment by zakriabilal** [comment] 2021-07-11 23:27
> this appears to be fixed by upgrading to `next ^11.0.1` and `next-pwa ^5.2.23`. I can confirm the /_next/static/ is being properly appended to imported images.
> 
> ![image](https://user-images.githubusercontent.com/36809369/125115201-d8ffd980-e09f-11eb-8e86-1f5a93ba9dd2.png)

This Fixed the error for me.

**Closed** 2021-07-25 06:55 UTC
Labels: bug, help wanted
