### ISSUE TITLE
Next 10.0.6 , Build Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by meotimdihia** [shadowwalker/next-pwa#151] opened 2021-01-30 02:28 UTC
# Summary

Next 10.0.6 , Build Error: Cannot find module 'webpack'

- C:\sources\a\node_modules\workbox-webpack-plugin\build\generate-sw.js
- C:\sources\a\node_modules\workbox-webpack-plugin\build\index.js
- C:\sources\a\node_modules\next-pwa\index.js
- C:\sources\a\next.config.js
- C:\sources\a\node_modules\next\dist\next-server\server\config.js
- C:\sources\a\node_modules\next\dist\build\index.js
- C:\sources\a\node_modules\next\dist\cli\next-build.js
- C:\sources\a\node_modules\next\dist\bin\next

# How To Reproduce

yarn build  with.:
- next: 10.0.6, 10.0.7
- next-pwa ^5.0.3

**Comment by otekdo** [comment] 2021-01-30 02:55
I also have this problem too!
The same exact response as you mentioned!
I had to **downgrade** to Next 10.0.5!

**Comment by champseo2017** [comment] 2021-01-30 04:56
I also have this problem too!

**Comment by srijanshetty** [comment] 2021-01-30 05:24
Same issues with my builds in GitHub Actions. This does not happen with local cached builds, but a new build always fails.

**Comment by ReeceM** [comment] 2021-01-31 14:21
So I just updated, and I have the same issue. 

But when trying to clear node_modules, package-lock.json and reinstalling, this is the following:

```bash
npm WARN babel-loader@8.2.2 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN clean-webpack-plugin@3.0.0 requires a peer of webpack@* but none is installed. You must install peer dependencies yourself.
npm WARN next-pwa@5.0.4 requires a peer of webpack@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN workbox-webpack-plugin@6.1.0 requires a peer of webpack@^4.4.0 || ^5.9.0 but none is installed. You must install peer dependencies yourself.
```

So, am I reading this correctly that nothing is installing web pack by default and that it's up to the end user to manage this bit?

#### Aside

I recall having this moving to version 10.0.5 last time, but cannot recall what actually fixed it.

**Comment by Divlo** [comment] 2021-02-01 18:39
This issue also has been reported to `vercel/next.js` repo : https://github.com/vercel/next.js/issues/21679
@otekdo Indeed downgrading to `next@10.0.5` solves the issue but it would be better to fix the issue with latest version of `next`.

Currently `next-pwa` depends of `webpack` in `peerDependencies` : https://github.com/shadowwalker/next-pwa/blob/9dc7c26716a1e5c20755f532fbc112501a463ce9/package.json#L27-L30

Maybe this commit is related : https://github.com/vercel/next.js/commit/099cd30b36cbd1dc3be6e3f9966a607100ea7dd4#diff-9c1a3867443c54525b4f24ef171f231a6e8bb065ffc8b7b62c4843d5ff62dd42L106-L108

Could be cool, if we find a solution for latest version of `next`.

**Comment by otekdo** [comment] 2021-02-01 18:57
@Divlo Thanks for the tip!
but right now, i'll keep it to 10.0.5, i'll wait for the solution
i do not really need 10.0.6, i updated because there could be some perfomance optimization or other stuff!

**Comment by shadowwalker** [comment] 2021-02-02 06:57
Try to add webpack with following command should help fix this issue:
```
yarn add webpack@webpack-4
```

**Comment by Divlo** [comment] 2021-02-02 08:16
@shadowwalker It solves the issue, but in my opinion `next` or `next-pwa` should handle this for us (users), as it was the case with `next@10.0.5`. We should not handle a `webpack` version in our `devDependencies`.
I don't know from where the error is coming from, and I don't know the codebase of this library, but I guess it's solvable without adding extra-dependencies for the users.

**Comment by carloscuesta** [comment] 2021-02-02 08:56
Totally agree with @Divlo that's something that `next` or `next-pwa` should handle. 

If I'm not mistaken, I think that what's happening here is that `next-pwa` assumes that `webpack` is a dependency that is satisfied by `next` that's why it's working at `10.0.5`

**Comment by ReeceM** [comment] 2021-02-02 10:13
I do believe that `next-pwa` uses workbox, and that is requiring `webpack` directly in the code that is throwing the error. 

I don't think this repo directly depends on it, but rather only has it as a development dependency, and is relying on the fact that the end user is using `webpack` and so is the `workbox` package. 

NextJS appears to have made the dependency of `webpack` handled internally and that removed the _natrual_ availability of the `webpack` package.

I see that there are requirements for peer dependencies in this package for `webpack`,  and I think the workbox one when installing.

@shadowwalker Is there the intention that the end user needs to have workbox installed? Or was it being statisfied as a requirement when NextJS was supplying Webpack and that the user initially didn't notice? (myself included)

**Comment by qipoy** [comment] 2021-02-02 10:15
I have no idea what's going on with webpack. I just roll back from `next@10.0.6` to `next@10.0.5` until this issue solved.

**Comment by shadowwalker** [comment] 2021-02-02 18:01
`next.js` should includes `webpack` and `next-pwa` will use that. This is how it works before, I'm not sure what's going on with latest changes and webpack 5 updates. Still investigating.

**Comment by ReeceM** [comment] 2021-02-02 18:11
> `next.js` should includes `webpack` and `next-pwa` will use that. This is how it works before, I'm not sure what's going on with latest changes and webpack 5 updates. Still investigating.

@shadowwalker what I noticed, between 10.0.6 canary-0 (this canary build works) and canary-1 `webpack` was removed as a dependency of nextjs and changed to an internally built and managed instance, so all referenced webpack instances that they used were changed to one under a `dist` directory. 

The thing that I noticed is that with `next-pwa` the error comes mainly from the workbox package as it requires an instance of web pack but still declares it under `devDependencies` So it isn’t really ever added in a end users node_modules folder. 

I am not sure if there is a way to reference the nextjs version and then declare it for workbox to find. But that would cause a similar issue as now. So that would be bad idea.

**Comment by timneutkens** [comment] 2021-02-02 20:05
Posted an explanation here: https://github.com/vercel/next.js/issues/21679#issuecomment-771941447

**Comment by BjoernRave** [comment] 2021-02-03 16:14
With the help of the explanation of @timneutkens I got it to work by adding `require('webpack')` to `next.config.js` and installing `webpack@4` as dependency

**Comment by timmalstead-cfa** [comment] 2021-02-03 19:24
I can confirm that the solution from @timneutkens and @BjoernRave works.

In my case, it was necessary to keep `next` at `10.0.5` and `next-pwa` at `5.0.3` and then install `webpack@4.4.0` under `devDependencies`.

Thanks so much!

**Comment by jatinhemnani01** [comment] 2021-02-04 15:08
so should I downgrade my next version to 10.0.5 ?

**Comment by shadowwalker** [comment] 2021-02-05 04:29
@timneutkens I read your comments here https://github.com/vercel/next.js/issues/21679#issuecomment-771941447, but still couldn't figure out what I should change in `next-pwa` to minimize the impact for the users of `next.js 10.0.6` and `next-pwa` plugin. Could you provide some more advice on this issue? Thanks.

**Comment by digitaltim-de** [comment] 2021-02-07 06:09
Same problem..

**Comment by ReeceM** [comment] 2021-02-07 10:49
As I had the issue coming from this package and `next.js` combined, the following was a solution: https://github.com/vercel/next.js/issues/21679#issuecomment-774652496

It seems that it will have to do until 10.0.7 of `next.js` comes out

**Comment by tarun1992** [comment] 2021-02-12 08:34
I am also facing the same issue. Is there any solution as Webpack solution didn't work for me.

**Comment by ReeceM** [comment] 2021-02-12 11:23
> I am also facing the same issue. Is there any solution as Webpack solution didn't work for me.

@tarun1992 maybe try Tim Neutkens suggestion as there is a patch in the canary version of nextjs, https://github.com/vercel/next.js/issues/21679#issuecomment-778112748

**Comment by Divlo** [comment] 2021-02-14 09:45
I tried https://github.com/vercel/next.js/issues/21679#issuecomment-778112748
So I use `next@10.0.7-canary.8` and `next-pwa@5.0.5` with `npm@6` because with `npm@7` the installation fails because the peer dependency are unmet.

But it isn't working, I still got the error :
```sh
Error: Cannot find module 'webpack'
Require stack:
- /home/divlo/Documents/Thream/website/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /home/divlo/Documents/Thream/website/node_modules/workbox-webpack-plugin/build/index.js
- /home/divlo/Documents/Thream/website/node_modules/next-pwa/index.js

...
etc.
```

**Comment by natbatwat** [comment] 2021-02-28 09:28
Facing the same issue with next 10.0.7

**Comment by leerle56** [comment] 2021-02-28 09:42
> Facing the same issue with next 10.0.7

I fix it by install webpack@4 in 10.0.7...

**Comment by Gilson401** [comment] 2021-03-01 19:54
Facing the same issue with next 10.0.1 (!)

**Comment by dcateflexera** [comment] 2021-03-04 15:13
I am still getting this issue with next v 10.0.7.

I added a `next.config.js` file to the root of the repo and the following code produces the error:

```
const withLess = require('@zeit/next-less')
  module.exports = withLess({
   /* config options here */
})
```

**Comment by carloscuesta** [comment] 2021-03-06 16:50
The issue is fixed at Next `10.0.8`, upgraded today from `10.0.5` and had no problems!

**Comment by meotimdihia** [comment] 2021-03-06 16:53
Yes, I think we can close this issue now.

**Comment by shadowwalker** [comment] 2021-03-07 06:21
Great, glad the issue is fixed with `next.js 10.0.8`. Please create a new issue if there are other concerns.

**Closed by shadowwalker** 2021-03-07 06:21 UTC
Labels: bug

**Comment by Hocdoc** [comment] 2021-03-16 07:27
I have to remove `node_modules`. After that, this error dissapeared:

```
rm -rf node_modules/
npm install
npm run build
```
