### ISSUE TITLE
How can i prevent import duplicated files ?

### ISSUE THREAD

**Issue by Flosrn** [shadowwalker/next-pwa#37] opened 2020-04-30 14:20 UTC
I use the [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images) module who convert to **webp** on the fly all my images. 

The problem is the service worker import twice file.. like this :
![Capture d’écran 2020-04-30 à 15 35 57](https://user-images.githubusercontent.com/12709355/80716972-9a17e080-8af8-11ea-8b16-28ab4f83ebde.png)
the .jpg and the .webp version

I would like to reduce the size of cache data and import all my images, except .wepb 

In my next.config.js I tried something like that: 
```
module.exports = withPlugins(
  [
    [
      withPWA,
      {
        pwa: {
          dest: "public",
          disable: process.env.NODE_ENV === "development",
          publicExcludes: ["([a-zA-Z0-9\\s_\\\\.\\-\\(\\):])+(.webp)$"]
        }
      }
    ],
    [...]
  ],
  nextConfig
);
```

But it seems it doesn’t work.

However I tested my regex expression and it works well here: https://regex101.com/r/CRiDxt/1

Someone would have an idea to solve my problem ? Thank you everyone

**Comment by Flosrn** [comment] 2020-04-30 19:56
Possible way of fix my problem: 
```
[
      withPWA,
      {
        pwa: {
          dest: "public",
          disable: process.env.NODE_ENV === "development",
          exclude: [/.*\.webp.*/]
        }
      }
    ],
```

It work (webp files are excluded) but I have an Error : 
```
workbox-e032be30.js:formatted:14 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://mydomain.now.sh/build-manifest.json","status":404}]
    at D (https://mydomain.now.sh/workbox-e032be30.js:1:11330)
    at async Promise.all (index 38)
    at async D.install (https://mydomain.now.sh/workbox-e032be30.js:1:10749)
```

**Comment by shadowwalker** [comment] 2020-05-08 04:53
@Flosrn You should use `publicExcludes` here, it doesn't support regex pattern, but it use glob pattern. Put something like this:
```
publicExcludes: ['!*.webp']
```

**Comment by Flosrn** [comment] 2020-05-08 06:30
> @Flosrn You should use `publicExcludes` here, it doesn't support regex pattern, but it use glob pattern. Put something like this:
> ```
> publicExcludes: ['!*.webp']
> ```

This is not work.. because my .webp files aren't in the public directory, only in .next folder after building

**Comment by shadowwalker** [comment] 2020-05-12 06:15
Please don't put generated `.webp` files or other static asset files into `.next/static` folder, it's not desired from development point of view.

**Comment by Flosrn** [comment] 2020-05-12 09:49
@shadowwalker it's the goal of [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images). 

> jpeg/png images can be converted to webp on the fly for an even smaller size
https://www.npmjs.com/package/next-optimized-images#webp

**Comment by Flosrn** [comment] 2020-06-07 08:18
@shadowwalker please can you reopen the issue ?

**Comment by shadowwalker** [comment] 2020-06-19 23:39
@Flosrn Just check in, are you still having the issue? If you need help, better to have a minimal error reproduce repo setup.

**Comment by chrsep** [comment] 2020-06-25 21:12
Hi, I seem to be encountering a similar issue. It looks like next-pwa is caching all of the images generated by next-optimized-images. This throws one of my [side project's](https://github.com/chrsep/grayson) initial page load from 52kb to over 800kb (tested by blocking the sw.js).

From what I've learned, since next-optimized-images uses webpack to process and generate the optimized images, the files it generates were automatically added to precache by workbox-webpack-plugin. so publicExcludes do not affect it.

What I found to be working though is to pass custom `exclude` property to next-pwa's config. But this would override next-pwa's built-in exclude rules, so I needed to copy the built-in exclude out to mine. This drops my initial page load to 234kb.
```js
     { 
        pwa: {
          disable: process.env.NODE_ENV === "development",
          dest: "public",
          precacheHomePage: false,
          exclude: [
            // next-pwa's rule
            ({ asset }) => {
              if (
                asset.name.match(
                  /^(build-manifest\.json|react-loadable-manifest\.json)$/
                )
              ) {
                return true
              }
              // TODO: not sure how to uncomment this, requires dev from webpack options. Fine if pwa is disabled on dev.
              // if (dev && !asset.name.startsWith("static/runtime/")) {
              //   return true
              // }
              return false
            },
            // Excludes all images, next-optimzed-images v3 generates them to \static\chunks\images by default
            // Having a custom next-optimized-images output folder might be better so that we can have a more specific regex
            /.*images.*$/,
          ],
        },
      },
```
Could next-pwa support an exclude option that extends the built in one? I could open a PR. Or is there a better solution?

##### Links
- Without exclude ([web](https://grayson-git-bug-huge-initial-load.chrsep.vercel.app/)) ([code](https://github.com/chrsep/grayson/pull/55))
- With exclude ([web](https://grayson-git-fix-huge-load.chrsep.now.sh/)) ([code](https://github.com/chrsep/grayson/pull/57))

**Comment by shadowwalker** [comment] 2020-06-27 05:24
It looks more sense to me that generated images are put into `public/static/images` folder instead of `.next/static/chunks/images`. Because that's the folder to serve all static assets. But when I try the configuration for `next-optimized-images`:
``` javascript
      {
        imagesPublicPath: "/static/images",
        imagesOutputPath: path.join(__dirname, "public/static/images"),
      }
```
It doesn't respect `imagesOutputPath` configuration. :(
I will add a options for you to resolve this issue.

**Comment by shadowwalker** [comment] 2020-06-27 06:08
Fixed with version `2.6.2`

**Closed** 2020-06-27 19:06 UTC
Labels: done

**Comment by Flosrn** [comment] 2020-07-01 04:51
For me the problem still the same in v2.6.2... 
Do you put a special configuration in your options ?

**Comment by chrsep** [comment] 2020-07-01 13:29
Yes, you'll still need to add a rule to exclude the files that you want to exclude on the config using the new buildExcludes attribute. I think something like this would work if you want to only exclude webp images generated by next-optimized-images

```js
{
  pwa: {
    buildExcludes: [/chunks\/images\/.*\.webp$/]
  }
}
```

**Comment by Flosrn** [comment] 2020-07-02 13:17
> Yes, you'll still need to add a rule to exclude the files that you want to exclude on the config using the new buildExcludes attribute. I think something like this would work if you want to only exclude webp images generated by next-optimized-images
> 
> ```js
> {
>   pwa: {
>     buildExcludes: [/chunks\/images\/.*\.webp$/]
>   }
> }
> ```

For me it work with this rule : 

`buildExcludes: [/images\/.*\.webp$/],`

Thank you for you efforts 🙏

**Comment by taniibarra** [comment] 2021-11-09 18:10
hi! i have the same problem, i need to prevent it from pre-caching the static/images as soon as it loads the pwa. I have them in a folder inside public/static/images.
This doesn't work for me: 
 [buildExcludes: [/chunks/images/.webp$/],
publicExcludes: ['!*.webp'],

**Comment by tajultonim** [comment] 2021-12-03 07:16
> Possible way of fix my problem:
> 
> ```
> [
>       withPWA,
>       {
>         pwa: {
>           dest: "public",
>           disable: process.env.NODE_ENV === "development",
>           exclude: [/.*\.webp.*/]
>         }
>       }
>     ],
> ```
> 
> It work (webp files are excluded) but I have an Error :
> 
> ```
> workbox-e032be30.js:formatted:14 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://mydomain.now.sh/build-manifest.json","status":404}]
>     at D (https://mydomain.now.sh/workbox-e032be30.js:1:11330)
>     at async Promise.all (index 38)
>     at async D.install (https://mydomain.now.sh/workbox-e032be30.js:1:10749)
> ```

I am also facing this error. Can you tell me how did you fixed it?
