### ISSUE TITLE
Workbox file logs error in the browser

### ISSUE THREAD

**Issue by akrmontoya** [shadowwalker/next-pwa#160] opened 2021-02-10 05:59 UTC
# Summary

I got 93/100 for "Best Practices" on Light house report because of "Browser errors were logged to the console" error. When I checked, it came from the workbox file generated by next-pwa.

# Screenshots

![Screenshot from 2021-02-10 13-58-59](https://user-images.githubusercontent.com/59873676/107471500-2d159900-6ba8-11eb-96f5-e9ad09c42500.png)

**Comment by kirkas** [comment] 2021-03-06 22:15
I am getting these as well when using Lighthouse!

Seems it's a common issue with [other PWA](https://github.com/nuxt-community/pwa-module/issues/176) plugins using workbox.js.
 
In short, it's a [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=823392) triggered by workbox.js

A [workaround](https://stackoverflow.com/questions/48463483/what-causes-a-failed-to-execute-fetch-on-serviceworkerglobalscope-only-if) has been found by [Paul Irish](https://github.com/paulirish/caltrainschedule.io/pull/51/commits/82d03d9c4468681421321db571d978d6adea45a7): He added this line to `sw.js`:
```
if (e.request.cache === 'only-if-cached' && e.request.mode !== 'same-origin') return;
```

the problem is that `sw.js` is generated automatically by next-pwa, so adding this fix is not currently possible AFAIK.

**Comment by TheMrZZ** [comment] 2021-03-25 14:15
Same here, however I've got 2 errors:
```
Uncaught (in promise) no-response: no-response :: [{"url":"https://myurl.com"}]
    at Object.I (https://myurl.com/workbox-a8b10d99.js:1:19214)
    at async Object.A (https://myurl.com/workbox-a8b10d99.js:1:11362)
s @ workbox-a8b10d99.js:1
I @ workbox-a8b10d99.js:1

workbox-a8b10d99.js:1 Uncaught (in promise) TypeError: Failed to fetch
  async function (async)
S @ workbox-a8b10d99.js:1
handleAll @ workbox-a8b10d99.js:1
handle @ workbox-a8b10d99.js:1
handleRequest @ workbox-a8b10d99.js:1
(anonymous) @ workbox-a8b10d99.js:1
```

Failed to fetch & no-response.

**Comment by shadowwalker** [comment] 2021-04-18 06:00
Fixed with latest version

**Closed by shadowwalker** 2021-04-18 06:00 UTC
Labels: bug, fixed
