### ISSUE TITLE
Wrong path in precaching from workbox

### ISSUE THREAD

**Issue by bravokiloecho** [shadowwalker/next-pwa#12] opened 2020-02-13 17:36 UTC
When I visit my exported site (by locally serving the `/out` directory) I get this error:

```
workbox-07643d7a.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:3000/public/pwa/android-chrome-144x144.png","status":404}]
    at D (http://localhost:3000/workbox-07643d7a.js:1:11361)
    at async Promise.all (index 0)
    at async D.install (http://localhost:3000/workbox-07643d7a.js:1:10780)
```

It seems to be looking in the `/public/pwa/` directory for the icons when they are in fact in the `/pwa/ directory.

My `manifest.json` is also in the `/pwa/` directory and looks like this:
```
{
  "name": "Name",
  "short_name": "Name",
  "description": "description",
  "dir": "auto",
  "lang": "en-US",
  "display": "standalone",
  "orientation": "any",
  "start_url": "/?homescreen=1",
  "background_color": "#fff",
  "theme_color": "#000",
  "icons": [
    {
      "src": "/pwa/android-chrome-36x36.png",
      "sizes": "36x36",
      "type": "image/png"
    },
   ...
  ]
}
```

How come this it's looking for icons in the starting in `public`?

Many thanks for any advice?

I'm using version 2..1.2 of this module with next 9.2.1

**Comment by shadowwalker** [comment] 2020-02-15 06:39
Can you share your `next.config.js` file and the `sw.js` file generated after the build?

**Comment by shadowwalker** [comment] 2020-02-15 07:06
@bravokiloecho

**Comment by bravokiloecho** [comment] 2020-02-17 10:05
This is the next config:
```
// Next plugins
const withPlugins = require('next-compose-plugins')
const withPWA = require('next-pwa')
// Webpack plugins
const FaviconsWebpackPlugin = require('favicons-webpack-plugin')
const dotenv = require('dotenv')

// Extract environment variables from local .env file
dotenv.config()

// SETUP FAVICON PLUGIN
const faviconPlugin = new FaviconsWebpackPlugin({
  logo: './public/icons/icon.svg',
  outputPath: '../public/pwa',
  prefix: 'pwa/',
  cache: true,
  inject: false,
  favicons: {
    appName: 'Name',
    appDescription: 'description',
    developerName: 'Name',
    developerUrl: 'https://test.com',
    background: '#fff',
    theme_color: '#000',
  },
})

// NEXT CONFIG
const nextConfig = {
  // Don't show if page can be optimised automatically
  // https://nextjs.org/docs/api-reference/next.config.js/static-optimization-indicator
  devIndicators: {
    autoPrerender: false,
  },
  // Custom webpack
  webpack: (config) => {
    config.plugins.push(faviconPlugin)
    return config
  },
}

module.exports = withPlugins([
  // add a plugin with specific configuration
  [withPWA, {
    pwa: {
      dest: 'public',
    },
  }],
], nextConfig)
```

**Comment by shadowwalker** [comment] 2020-02-18 07:21
``` javascript
// SETUP FAVICON PLUGIN
const faviconPlugin = new FaviconsWebpackPlugin({
  logo: './public/icons/icon.svg',
  outputPath: '../public/pwa',
  prefix: 'pwa/',
  cache: true,
  ...
```
Looks like the the favicons are generated in `public/public/pwa`, you may want to try to change `outputPath` to `../../public/pwa`

**Comment by bravokiloecho** [comment] 2020-02-18 12:44
I don't think that was the issue.

It seems like the workbox script is looking for the PWA icons in `/public/pwa/` when they are actually in `/pwa/` (see image below). I've tried setting the scope prop manually to `/` but that didn't do anything..

![image](https://user-images.githubusercontent.com/5556900/74737105-1023df80-524c-11ea-827f-63442c7c84f1.png)

**Comment by bravokiloecho** [comment] 2020-02-18 13:02
It looks like it's trying to read the `outputPath` from the favicons-webpack-plugin but this is not helping! Is there any reason why it's interacting wit this?

**Comment by shadowwalker** [comment] 2020-02-18 21:16
Are you using custom server to host files in `public` folder? Or just use `next start` to start the server?
I couldn't see a reason this should happen. Have you also tried clear all site data in dev tools and do a hard reload?

**Comment by haoict** [comment] 2020-02-19 06:24
I also have the same problem, I use Next.js 9+ and serve service worker from public folder.
In `/sw.js`, there is undefined like this
![image](https://user-images.githubusercontent.com/7247750/74807437-cca0a280-532b-11ea-84f7-2f60138d0f52.png)

next.config.js
```
module.exports = withPWA({
      pwa: {
        dest: 'public'
      },
     ...
```

/public/manifest.json
```
{
  "name": "Next Dict",
  "short_name": "Next Dict",
  "theme_color": "#c40012",
  "background_color": "#c40012",
  "display": "standalone",
  "Scope": "/",
  "start_url": "/",
  ...
}
```

**Comment by haoict** [comment] 2020-02-19 08:00
I found a temporary fix for above issue.
In next.config.js, I set
```
withPWA({
      pwa: {
        dest: 'public',

        modifyURLPrefix: {
          'undefinedstatic/': '_next/static/'
        }
      },
```

so it replaces `undefinedstatic/` with correct path `_next/static/`.
Probably WorkboxPlugin.GenerateSW can not set correct _next build folder, so it is undefined

**Comment by shadowwalker** [comment] 2020-02-20 01:07
@haoict are you defining additional `webpack` configuration in your `next.config.js`?
@bravokiloecho I might have a clue of the problem now, it is because webpack config is overrided in the `next-pwa`, will try to repro and fix it.

**Comment by haoict** [comment] 2020-02-20 02:34
@shadowwalker oh.. yeah. I think I have this custom configuration that causes the issue.

```
const {  ASSET_HOST } = process.env;

// for those who using CDN
const assetPrefix = ASSET_HOST || '';

module.exports = withPWA({
  webpack: (config, { dev }) => {
        config.node = { fs: 'empty' };
        config.output.publicPath = `${assetPrefix}${config.output.publicPath}`;   <= HERE
  }
})
```

**Comment by shadowwalker** [comment] 2020-02-20 03:21
@bravokiloecho Please add following to `next.config.js` pwa configuration unblock you for now:
``` javascript
module.exports = withPlugins([
  [withPWA, {
    pwa: {
      dest: 'public',
      modifyURLPrefix: {
        'static/': '_next/static/',
        '../public/': '/'
      }
    },
  }],
], nextConfig)
```

**Comment by shadowwalker** [comment] 2020-02-20 22:07
@bravokiloecho The issue is fixed now, update the version of `next-pwa` then run `yarn build`, if you want to precache all the icons generated, run `yarn build` one more time, it will pick up the files generated in `public` folder.
@haoict Also I fix the issue with publicPath, it more fault tolerant now.

**Closed by shadowwalker** 2020-02-20 22:07 UTC
