### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by Ethan-Hill** [shadowwalker/next-pwa#140] opened 2021-01-18 10:37 UTC
# Summary

What can I help with? Please keep this clear and concise.

When trying to build my project with next-pwa I get this error.

```
❯ npx next build
Loaded env from C:\Users\Ethan\Documents\GitHub\nexify\.env.local
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next-pwa\register.js
> [PWA] Service worker: C:\Users\Ethan\Documents\GitHub\nexify\.next\sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server

> Build error occurred
TypeError: Cannot read property 'tapPromise' of undefined
    at C:\Users\Ethan\Documents\GitHub\nexify\node_modules\workbox-webpack-plugin\build\generate-sw.js:242:41
    at SyncHook.eval [as call] (eval at create (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:630:30)
    at C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:662:28)
    at C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:321:11
    at Compiler.readRecords (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:529:11)
    at C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next\node_modules\webpack\lib\Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Ethan\Documents\GitHub\nexify\node_modules\tapable\lib\Hook.js:154:20)
info  - Creating an optimized production build .
```

# How To Reproduce

1. yarn add next-pwa
2. Edit next config

```
var path = require("path");
const withPWA = require("next-pwa");
module.exports = withPWA({
  resolve: {
    modules: ["node_modules", "js"],
    alias: {
      "mapbox-gl": path.resolve("./node_modules/mapbox-gl/dist/mapbox-gl.js"),
    },
  },

  functions: {
    "api/auth/[...nextauth]": {
      maxDuration: 30,
    },
  },
});
```

3. yarn build

# Screenshots
![WindowsTerminal_4jcqNFxMqK](https://user-images.githubusercontent.com/45304268/104904520-24e78680-5979-11eb-98f5-077d38a70977.png)

**Comment by shadowwalker** [comment] 2021-01-19 05:06
Duplicate of #138

**Comment by Ethan-Hill** [comment] 2021-01-19 10:42
Alright, i was able to fix it by removing the `webpack` dependency.

It does build with it but I'm not able to download the PWA even though it does build with it.

```
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: C:\Users\Ethan\Documents\GitHub\nexify\node_modules\next-pwa\register.js
> [PWA] Service worker: C:\Users\Ethan\Documents\GitHub\nexify\public\sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server
info  - Creating an optimized production build
info  - Compiled successfully
````

next config
```
var path = require("path");
const withPWA = require("next-pwa");

const settings = {
  resolve: {
    modules: ["node_modules", "js"],
    alias: {
      "mapbox-gl": path.resolve("./node_modules/mapbox-gl/dist/mapbox-gl.js"),
    },
  },

  functions: {
    "api/auth/[...nextauth]": {
      maxDuration: 30,
    },
  },
  devIndicators: {
    autoPrerender: false,
  },
  pwa: {
    dest: "public",
  },
};

module.exports =
  process.env.NODE_ENV === "development" ? settings : withPWA(settings);
```

**Comment by Ethan-Hill** [comment] 2021-01-19 11:00
![chrome_nuXVqhBuQW](https://user-images.githubusercontent.com/45304268/105025384-2aaa9e00-5a45-11eb-933e-42ffef627dee.png)

The SW is found on the website source as well
 
![chrome_yxX0CpNpgJ](https://user-images.githubusercontent.com/45304268/105025618-7d845580-5a45-11eb-80e2-b66a13b2c56b.png)

**Comment by shadowwalker** [comment] 2021-01-19 22:24
You are missing `manifest.json` in your head meta

``` html
<link rel='manifest' href='/manifest.json' />
```

**Comment by Ethan-Hill** [comment] 2021-01-26 17:28
![image](https://user-images.githubusercontent.com/45304268/105880593-6f14db80-5ffb-11eb-86a1-a092d6fa89fb.png)
![image](https://user-images.githubusercontent.com/45304268/105880695-9370b800-5ffb-11eb-9689-38ef0746673a.png)
![image](https://user-images.githubusercontent.com/45304268/105880758-a3889780-5ffb-11eb-87e6-d1411f1b909f.png)

```js
const withPWA = require("next-pwa");
const path = require("path");
const CopyPlugin = require('copy-webpack-plugin');

const settings = {
  functions: {
    "api/auth/[...nextauth]": {
      maxDuration: 30,
    },
  },
  devIndicators: {
    autoPrerender: false,
  },
  pwa: {
    dest: "public",
    register: true,
    scope: "/src",
  },

  webpack:(config) => {config.plugins.push(  new CopyPlugin({
	patterns: [
	  {
		from: path.resolve(__dirname, 'node_modules/@shoelace-style/shoelace/dist/shoelace/icons'),
		to: path.resolve(__dirname, 'static/icons')
	  }
	]
  }))
  return config
}

};

module.exports =
  process.env.NODE_ENV === "development" ? settings : withPWA(settings);
```

I have the manifest there now and it still does not seem to want to be a PWA.

**Comment by shadowwalker** [comment] 2021-02-02 05:22
OK, I found a few problems when I visit your web app at http://nexify.vercel.app

1. Remove `scope: "/src",` in your pwa config in `next.config.js` file, you should keep this as default "/"
2. When I visit your web app, after the service worker downloaded, it starts precache resources before being active, which is **A LOT** in your case. See it below, it took me 4.5 minutes to fully download all the resources and activate the service worker.

![image](https://user-images.githubusercontent.com/9603375/106555668-d981bc00-64d2-11eb-8562-c5c128a2ac94.png)

3. Look at the https://nexify.vercel.app/sw.js file, you will see a lot of entries for precache. You should only put what you need in the public folder or use `publicExcludes` config to limit resources need to be pre cached.

**Closed** 2021-04-04 14:16 UTC
Labels: question
