### ISSUE TITLE
I want to add a custom snackbar, for New Update available of the website. Refresh

### ISSUE THREAD

**Issue by guptamohit004** [shadowwalker/next-pwa#83] opened 2020-07-17 08:10 UTC
I'm using next-pwa everything is working fine.
One thing I need to add is New Version Available Like this - 

Please tell how can I do this ?

![powoo4ao9l0gdunk30sc](https://user-images.githubusercontent.com/33790761/87764032-5600c600-c833-11ea-99ea-dd32598d7530.gif)

**Comment by shadowwalker** [comment] 2020-07-19 06:12
Duplicate of #81

**Closed by shadowwalker** 2020-07-19 06:12 UTC

**Comment by shadowwalker** [comment] 2020-07-19 18:58
Please see in this example

https://github.com/shadowwalker/next-pwa/blob/1e8482c46f9dae12e7f10f01bc12a1614d359990/examples/lifecycle/pages/index.js#L27-L49
