### ISSUE TITLE
The start_url did respond, but not via a service worker.

### ISSUE THREAD

**Issue by jamiljaar** [shadowwalker/next-pwa#130] opened 2020-12-10 22:21 UTC
# Summary
Lighthouse reports overall are great, but no matter what I try, the PWA section always throws this error:

"The start_url did respond, but not via a service worker."

Everything else regarding PWA is green. PWA capabilities seem to be working completely and as expected. I would just like to be sure I'm not missing something that might cause unforeseen issues.

# How To Reproduce
1. Running on Next.js 10 (although it happened on 9 as well).
2. Included an exhaustive manifest.json as well as its assets in the 'public' folder.
3. Included all the necessary meta and link tags in the '_document.js' file.
4. My 'next.config.js' file exports the config within 'withPWA()', and the only config in there is the 'dest': 'public' in 'pwa'.

# Expected Behaviors
Lighthouse should show all criteria for PWA as checked.

**Comment by shadowwalker** [comment] 2020-12-11 04:28
Duplicate of #124

**Closed by shadowwalker** 2020-12-11 04:28 UTC
Labels: bug
